/* tslint:disable */
/* eslint-disable */
/**
 * GEWISDB API
 * The GEWIS member database has a few available endpoints
 *
 * The version of the OpenAPI document: 61a3f816c126d454d7bd665dd6788f9d7a619961
 * Contact: abc@gewis.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

