/* tslint:disable */
/* eslint-disable */
/**
 * GEWISDB API
 * The GEWIS member database has a few available endpoints
 *
 * The version of the OpenAPI document: 86c08a87afe939cbb9a515f7063965f7bdb30bce
 * Contact: abc@gewis.nl
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

